"""Correct

Revision ID: eac0decaf4f5
Revises: 3b519f7b81b7
Create Date: 2025-05-28 17:30:11.982115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac0decaf4f5'
down_revision: Union[str, None] = '3b519f7b81b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('history_country_key'), 'history', type_='unique')
    op.create_unique_constraint(None, 'history', ['id'])
    op.create_unique_constraint(None, 'users_histories', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_histories', type_='unique')
    op.drop_constraint(None, 'history', type_='unique')
    op.create_unique_constraint(op.f('history_country_key'), 'history', ['country'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
